name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install actionlint
        env:
          ACTIONLINT_VERSION: "1.7.12"
        run: |
          curl -fsSLO "https://raw.githubusercontent.com/rhysd/actionlint/v${ACTIONLINT_VERSION}/scripts/download-actionlint.bash"
          bash download-actionlint.bash "${ACTIONLINT_VERSION}"
          echo "$PWD" >> "$GITHUB_PATH"
      - name: Lint workflows and actions
        run: actionlint -color
